In [20]:
import numpy as np

In [21]:
months = ['January', 'February', 'March']
product_categories = ['Electronics', 'Clothing']
geographical_regions = ['North', 'South']


In [22]:
sales_data = np.random.randint(1000, 10000, size=(3, 2, 2))

In [23]:
print("Sample sales data:")
print(sales_data)

Sample sales data:
[[[5047 1440]
  [2309 2448]]

 [[1315 9287]
  [5672 1503]]

 [[2113 9807]
  [6951 9622]]]


In [ ]:
sales_by_month = np.sum(sales_data, axis=(1, 2))


In [ ]:
sales_by_category = np.sum(sales_data, axis=(0, 2))

In [ ]:
sales_by_region = np.sum(sales_data, axis=(0, 1))

In [ ]:
print("\nSales by month:")
print(sales_by_month)


Sales by month:
[32631 30278  9606]


In [ ]:
print("\nSales by product category:")
print(sales_by_category)



Sales by product category:
[34155 38360]


In [ ]:
print("\nSales by geographical region:")
print(sales_by_region)


Sales by geographical region:
[38519 33996]
